export const environment = {
    dotcmsUrl: "dotcms-qa-master.dotcms.site",
    authToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGllZjg0NzhjOS0yMWUzLTQyODMtYTI4Ni0yYWY3MDI4MWU4NjgiLCJ4bW9kIjoxNzE1MDMxOTc0MDAwLCJuYmYiOjE3MTUwMzE5NzQsImlzcyI6ImRvdGNtcy1xYS1tYXN0ZXIiLCJsYWJlbCI6InZlcmNlbCIsImV4cCI6MTgwOTU4MzIwMCwiaWF0IjoxNzE1MDMxOTc0LCJqdGkiOiIyOWUyMTEwMC00ODkzLTRiZDItYTc2My03NWNmMTIwZjQzNGIifQ.1k4ylvpBjr5PRKPvDAIawEIX5gSZLWAn-D1paKH9UCc",
    siteId: "true",
};
